# Script path in zsh: "${(%):-%x}"
source $DOTFILES/common.sh
source $DOTFILES/zshrc

setup_aliases
setup_colors

ssh_add_keys $HOME/.ssh/id_rsa

#export BASH_SILENCE_DEPRECATION_WARNING=1
alias py=python3

# Add homebrew sbin, ~/bin, and cargo bin dir to path
export PATH="/usr/local/sbin:$HOME/bin:$HOME/.cargo/bin:$PATH"
export GOPATH="$HOME/go"
setup_dedup_path

# lazy-load nvm command
nvm () {
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    nvm $*
}

